### ISSUE TITLE
tensor compatibility error

### ISSUE THREAD

**Issue by zer0deck** [zer0deck/transformer_chatbot#2]
Ran into problem during the work on `sparse_categorical_f1` fuction implementation:
[../chatbot/transformer.py:179](https://github.com/zer0deck/transformer_chatbot/blob/main/chatbot/transformer.py#L179)

The problem is I have old `onehot_categorical_f1` realization:

```python
def f1(y_pred, y_true):
    true_positives = tf.keras.backend.sum(tf.keras.backend.round(tf.keras.backend.clip(y_true * y_pred, 0, 1)))
    possible_positives = tf.keras.backend.sum(tf.keras.backend.round(tf.keras.backend.clip(y_true, 0, 1)))
    predicted_positives = tf.keras.backend.sum(tf.keras.backend.round(tf.keras.backend.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + tf.keras.backend.epsilon())
    recall = true_positives / (possible_positives + tf.keras.backend.epsilon())
    f1_score = 2*(precision*recall)/(precision+recall+tf.keras.backend.epsilon())
return f1_score
```

but this implementation **requires `y_true` and `y_pred` to be numpy `ndarray`**, but I only have `tf.Tensor` objects as  `y_true` and `y_pred`.
Trying to use `y_true.numpy()` with activated `Eager mode`, but got this error:

```python
File d:\Users\zer0deck\Documents\Work\python\SW\transformer_chatbot\chatbot\transformer.py:300, in Transformer.fit(self, data, path)
    297 self._model.compile(optimizer=self._optimizer, loss=self._count_loss, metrics=[self._count_accuracy, self._count_f1])
    299 print(f"{self._model} compiled successfully.")
--> 300 self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)

File c:\ProgramData\miniforge3\envs\tfenv\lib\site-packages\keras\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~\AppData\Local\Temp\__autograph_generated_filekkz9d3st.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False
...
    File "d:\Users\zer0deck\Documents\Work\python\SW\transformer_chatbot\chatbot\transformer.py", line 183, in _count_f1  *
        y_true.numpy()

    AttributeError: 'Tensor' object has no attribute 'numpy'
```

**But using anything like `tf.compat.v1.Session()` returns this:**

```python
InvalidArgumentError                      Traceback (most recent call last)
Cell In [3], line 1
----> 1 tf.fit(path='data/conv-ai-2017')

File d:\Users\zer0deck\Documents\Work\python\SW\transformer_chatbot\chatbot\transformer.py:297, in Transformer.fit(self, data, path)
    294 self._model.compile(optimizer=self._optimizer, loss=self._count_loss, metrics=[self._count_accuracy, self._count_f1])
    296 print(f"{self._model} compiled successfully.")
--> 297 self._model.fit(self._data_controller.dataset, epochs=self.num_epoch)

File c:\ProgramData\miniforge3\envs\tfenv\lib\site-packages\keras\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File c:\ProgramData\miniforge3\envs\tfenv\lib\site-packages\tensorflow\python\framework\func_graph.py:1233, in func_graph_from_py_func.<locals>.autograph_handler(*args, **kwargs)
   1231 except Exception as e:  # pylint:disable=broad-except
   1232   if hasattr(e, "ag_error_metadata"):
-> 1233     raise e.ag_error_metadata.to_exception(e)
   1234   else:
   1235     raise
...
  File "c:\ProgramData\miniforge3\envs\tfenv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 735, in _create_op_internal
    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
  File "c:\ProgramData\miniforge3\envs\tfenv\lib\site-packages\tensorflow\python\framework\ops.py", line 3800, in _create_op_internal
    ret = Operation(
```

***IDK what to do, the only thing I need is to get `ndarray` or `list` or smth else from  `tf.Tensor`.***

**Comment by zer0deck** [comment]
[Branch link connected](https://github.com/zer0deck/transformer_chatbot/tree/2-tensor-compatibility-error), thk my friend for idea of type converting.

***Now the issue is to find `tf.function()` to change `<tf.Tensor, numpy= [2, 1, 3]>` into `<tf.Tensor, numpy=[[0,0,1,0],[0,1,0,0],[0,0,0,1]]>`***
